// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BalanceCard from "../components/BalanceCard.res.mjs";
import * as ExpenseHistory from "../components/ExpenseHistory.res.mjs";
import * as AddNewTransaction from "../components/AddNewTransaction.res.mjs";
import * as IncomeExpenseCard from "../components/IncomeExpenseCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ExpenseForm(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Expense Tracker"
                    }),
                JsxRuntime.jsx(BalanceCard.make, {}),
                JsxRuntime.jsx(IncomeExpenseCard.make, {}),
                JsxRuntime.jsx(ExpenseHistory.make, {}),
                JsxRuntime.jsx(AddNewTransaction.make, {})
              ],
              className: "w-1/3  m-auto"
            });
}

var make = ExpenseForm;

export {
  make ,
}
/* BalanceCard Not a pure module */
