// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BalanceCard from "../components/BalanceCard.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ExpenseHistory from "../components/ExpenseHistory.res.mjs";
import * as AddNewTransaction from "../components/AddNewTransaction.res.mjs";
import * as IncomeExpenseCard from "../components/IncomeExpenseCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var t = localStorage;

function saveToLocalStorage(key, value) {
  t.setItem(key, value);
}

function ExpenseForm(props) {
  var defaultTransactionData_transactions = [];
  var defaultTransactionData = {
    income: 0.0,
    expense: 0.0,
    transactions: defaultTransactionData_transactions
  };
  var defaultTransactionDataString = JSON.stringify(defaultTransactionData);
  var localStorageData = t.getItem("transcationsData");
  var parsedLocalStorageData = JSON.parse(Belt_Option.getWithDefault(localStorageData === null ? undefined : Caml_option.some(localStorageData), Belt_Option.getWithDefault(defaultTransactionDataString, "")));
  console.log(parsedLocalStorageData);
  React.useState(function () {
        return defaultTransactionData;
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Expense Tracker"
                    }),
                JsxRuntime.jsx(BalanceCard.make, {}),
                JsxRuntime.jsx(IncomeExpenseCard.make, {}),
                JsxRuntime.jsx(AddNewTransaction.make, {}),
                JsxRuntime.jsx(ExpenseHistory.make, {})
              ],
              className: "w-1/3  m-auto"
            });
}

var make = ExpenseForm;

export {
  t ,
  saveToLocalStorage ,
  make ,
}
/* t Not a pure module */
