// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Constants from "../utils/constants.res.mjs";
import * as BalanceCard from "../components/BalanceCard.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ExpenseHistory from "../components/ExpenseHistory.res.mjs";
import * as AddNewTransaction from "../components/AddNewTransaction.res.mjs";
import * as IncomeExpenseCard from "../components/IncomeExpenseCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var t = localStorage;

function saveToLocalStorage(key, value) {
  t.setItem(key, value);
}

function ExpenseForm(props) {
  var defaultTransactionDataString = JSON.stringify(Constants.defaultTransactionData);
  var localStorageData = t.getItem("transcationsData");
  var parsedLocalStorageData = JSON.parse(Belt_Option.getWithDefault(localStorageData === null ? undefined : Caml_option.some(localStorageData), Belt_Option.getWithDefault(defaultTransactionDataString, "")));
  var match = React.useState(function () {
        return parsedLocalStorageData;
      });
  var expenseFormData = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Expense Tracker"
                    }),
                JsxRuntime.jsx(BalanceCard.make, {
                      balance: expenseFormData.expense + expenseFormData.income
                    }),
                JsxRuntime.jsx(IncomeExpenseCard.make, {
                      income: expenseFormData.income,
                      expense: expenseFormData.expense
                    }),
                JsxRuntime.jsx(AddNewTransaction.make, {
                      data: expenseFormData,
                      onNewTransaction: match[1]
                    }),
                JsxRuntime.jsx(ExpenseHistory.make, {})
              ],
              className: "w-1/3  m-auto"
            });
}

var make = ExpenseForm;

export {
  t ,
  saveToLocalStorage ,
  make ,
}
/* t Not a pure module */
