// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TransactionForm from "./TransactionForm.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function AddNewTransaction(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Add new transaction",
                      className: "font-bold text-lg"
                    }),
                JsxRuntime.jsx(TransactionForm.make, {})
              ]
            });
}

var make = AddNewTransaction;

export {
  make ,
}
/* TransactionForm Not a pure module */
