// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AmountInputField(props) {
  var onChange = props.onChange;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("span", {
                      children: [
                        "Amount",
                        JsxRuntime.jsx("span", {
                              children: "(-ve value for debit and +v value for credit)"
                            })
                      ]
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("input", {
                            className: "w-full outline-none ",
                            placeholder: "Enter amount",
                            type: "number",
                            value: props.value,
                            onChange: (function (ev) {
                                var target = ev.target;
                                var value = target.value;
                                onChange(value);
                              })
                          }),
                      className: "border-slate-400 border-[1px]  rounded p-2 w-full flex self-center"
                    })
              ]
            });
}

var make = AmountInputField;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
