// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AmountInputField(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: "Amount"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("span", {
                              children: "+",
                              className: "pr-2 text-2xl"
                            }),
                        JsxRuntime.jsx("input", {
                              className: "w-full outline-none ",
                              placeholder: "Enter amount",
                              type: "number"
                            })
                      ],
                      className: "border-slate-400 border-[1px]  rounded p-2 w-full flex self-center"
                    })
              ]
            });
}

var make = AmountInputField;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
