// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as JsxRuntime from "react/jsx-runtime";

function BalanceCard(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "YOUR BALANCE"
                    }),
                JsxRuntime.jsxs("p", {
                      children: [
                        JsxRuntime.jsx("span", {
                              children: "+",
                              className: "font-bold text-emerald-600"
                            }),
                        "₹",
                        PervasivesU.abs(10000)
                      ],
                      className: "font-bold text-emerald-600"
                    })
              ],
              className: "flex flex-col items-center"
            });
}

var make = BalanceCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
