// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CustomDropDown from "./CustomDropDown.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ExpenseCategoryInput(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: "Expense Category"
                    }),
                JsxRuntime.jsx(CustomDropDown.make, {})
              ]
            });
}

var make = ExpenseCategoryInput;

export {
  make ,
}
/* CustomDropDown Not a pure module */
