// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SingleHistoryItem from "./singleHistoryItem.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ExpenseHistory(props) {
  var match = React.useState(function () {
        return true;
      });
  var setShowHistory = match[1];
  var showHistory = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("h1", {
                            children: "Expense History",
                            className: "font-bold text-lg"
                          }),
                      className: "bg-slate-100 flex flex-row justify-between p-2 cursor-pointer",
                      onClick: (function (param) {
                          setShowHistory(function (param) {
                                return !showHistory;
                              });
                        })
                    }),
                showHistory ? JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {}),
                          JsxRuntime.jsx(SingleHistoryItem.make, {})
                        ],
                        className: "divide-y divide-slate-200"
                      }) : JsxRuntime.jsx(JsxRuntime.Fragment, {})
              ],
              className: "mt-5"
            });
}

var make = ExpenseHistory;

export {
  make ,
}
/* react Not a pure module */
