// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Input(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("input", {
                    className: "border",
                    type: "number"
                  }),
              className: "p-6"
            });
}

var make = Input;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
