// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function SingleHistoryItem(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("span", {
                              children: "Salary",
                              className: "m-2"
                            }),
                        JsxRuntime.jsx("span", {
                              children: "💵"
                            })
                      ],
                      className: "items-center"
                    }),
                JsxRuntime.jsx("div", {
                      children: -10000
                    })
              ],
              className: "flex flex-row justify-between  m-2 p-2  border-1  border-r-red-500 border-r-4"
            });
}

var make = SingleHistoryItem;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
