// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AmountInputField from "./AmountInputField.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ExpenseCategoryInput from "./ExpenseCategoryInput.res.mjs";

function TransactionForm(props) {
  var match = React.useState(function () {
        return "";
      });
  var setTransactionAmount = match[1];
  var handleTransactionAmountChange = function (val) {
    setTransactionAmount(function (param) {
          return val;
        });
  };
  var match$1 = React.useState(function () {
        return "";
      });
  var setTransactionCategory = match$1[1];
  var handleTransactionCatChange = function (val) {
    setTransactionCategory(function (param) {
          return val;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(ExpenseCategoryInput.make, {
                      value: match$1[0],
                      onChange: handleTransactionCatChange
                    }),
                JsxRuntime.jsx(AmountInputField.make, {
                      value: match[0],
                      onChange: handleTransactionAmountChange
                    }),
                JsxRuntime.jsx("button", {
                      children: "Add Transaction",
                      className: "bg-emerald-400 w-full p-2 font-bold rounded hover:bg-emerald-600"
                    })
              ]
            });
}

var make = TransactionForm;

export {
  make ,
}
/* react Not a pure module */
