// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TransactionForm(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Add Input Fields "
                    }),
                JsxRuntime.jsx("button", {
                      children: "Add Transaction",
                      className: "bg-emerald-400 w-full p-2 font-bold rounded hover:bg-emerald-600"
                    })
              ]
            });
}

var make = TransactionForm;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
