// Generated by ReScript, PLEASE EDIT WITH CARE


var t = localStorage;

function saveToLocalStorage(key, value) {
  t.setItem(key, "value");
}

export {
  t ,
  saveToLocalStorage ,
}
/* t Not a pure module */
