// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ExpenseForm from "./pages/ExpenseForm.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(ExpenseForm.make, {}),
              className: "p-6 "
            });
}

var make = App;

export {
  make ,
}
/* ExpenseForm Not a pure module */
