// Generated by ReScript, PLEASE EDIT WITH CARE


var items = [
  {
    title: "Item 1",
    description: "This is the first item."
  },
  {
    title: "Item 2",
    description: "This is the second item."
  },
  {
    title: "Item 3",
    description: "This is the third item."
  }
];

export {
  items ,
}
/* No side effect */
